networks:
    default:
        ipam:
            config:
                - subnet: 10.5.0.0/16
                  gateway: 10.5.0.1
services:
    haproxy:
        build: haproxy
        container_name: haproxy
        volumes:
            - ./haproxy/conf/:/usr/local/etc/haproxy/
            - ./haproxy/ssl/:/etc/ssl/xip.io/
        ports:
            - "80:80"
            - "443:443"
        networks: 
            default:
                ipv4_address: 10.5.0.3
    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
        ports:
            - "5432:5432"
        volumes:
            - ./postgres/sql:/docker-entrypoint-initdb.d
            - ./postgres/data:/var/lib/postgresql/data
        networks: 
            default:
                ipv4_address: 10.5.0.4
    # nginx:
    #     image: nginx:1.13
    #     restart: always
    #     ports:
    #         - "80:80"
    #         - "9090:9090"
    #     networks:
    #         default:
    #             ipv4_address: 10.5.0.3
    #     volumes: 
    #         - "./nginx/conf.d:/etc/nginx/conf.d"

    testwebapp:
        build: testwebapp
        container_name: testwebapp
        environment:
            - CATALINA_OPTS=-Xmx12g -Xms12g -XX:MaxPermSize=4096m -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -XX:+UseConcMarkSweepGC
            - JVM_OPTS=-Xmx12g -Xms12g -XX:MaxPermSize=4096m -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -XX:+UseConcMarkSweepGC
            - JAVA_OPTS=
            - SPRING_DATASOURCE_URL=jdbc:postgresql://10.5.0.4:5432/testwebapp?user=testwebapp
            - SPRING_DATASOURCE_USERNAME=testwebapp
            - SPRING_DATASOURCE_PASSWORD=testwebapp
        ports: 
            - "8080:8080"
        networks:
            default:
                ipv4_address: 10.5.0.2
        depends_on: 
            - haproxy
            - postgres
        restart: always
version: '2'